scaleout: 300
chunksize: 20000
mem-per-worker: "6GB"
disk-per-worker: "4GB"
cores-per-worker: 1
adaptive: false
queue: "workday"
walltime: "12:00:00"
performance-report: false
custom-setup-commands: null
conda-env: false
death-timeout: "3600"
worker-image: "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-analysis/general/pocketcoffea:lxplus-el9-latest"
local-virtualenv: true
spanet_model: "/eos/user/m/mmarcheg/ttHbb/models/spanet_v2/multiple_binary_classifiers_btag_LMH/spanet_output/version_epoch62/spanet.onnx"
dctr_model: "/eos/user/m/mmarcheg/ttHbb/dctr/training/spanet_v2/tthbb_0p40To0p75/features_8/binary_classifier_full_Run2_batch8092_lr5e-3/lightning_logs/version_0/model.onnx"
