object_preselection:
  JetGood:
    pt: 25
    pt_tight: 35
    eta: 2.5
    jetId: 6 # 6 with lepveto or 2 w/o lepveto
    btagPNetB: -2 
    #TODO: trigger matching?
  Electron:
    pt: 15
    eta: 2.4
    id: mvaIso_WP80 #TODO mvaIso_WPL iso / no iso # loose not in nanoaodv12
    iso: 0.15 # 0.3? #DeltaR=0.3
    dxy_barrel: 0.05
    dz_barrel: 0.1
    dxy_endcap: 0.1
    dz_endcap: 0.2
  Muon:
    pt: 10
    eta: 2.4
    id: looseId
    iso: 0.15 # 0.3? #DeltaR=0.3
    dxy_barrel: 0.05
    dz_barrel: 0.1
    dxy_endcap: 0.1
    dz_endcap: 0.2
  JetGoodVBF:
    pt: 25
    eta_min: 2.5
    eta_max: 4.7
    jetId: 6 # 6 with lepveto or 2 w/o lepveto
    btagPNetB: -2 # 0.2605
  JetVBF_generalSelection:
    pt: 10
    eta: 4.7
    jetId: 6 # 6 with lepveto or 2 w/o lepveto
    btagPNetB: -2 # 0.2605
  JetVBFNotFromHiggs:
    pt: 10
    eta: 4.7
    jetId: 6 # 6 with lepveto or 2 w/o lepveto
    btagPNetB: -2 # 0.2605
  JetVBF_matching:
    pt: 0
    eta: 10
    jetId: 6 # 6 with lepveto or 2 w/o lepveto
    btagPNetB: -2 # 0.2605