plotting_style:
  labels_mc:
    TTToSemiLeptonic__TTToSemiLeptonic_tt+LF: "$t\\bar{t}$+LF (5FS)"
    TTToSemiLeptonic__TTToSemiLeptonic_tt+C: "$t\\bar{t}$+C (5FS)"
    TTToSemiLeptonic__TTToSemiLeptonic_tt+B: "$t\\bar{t}$+B (5FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+LF: "$t\\bar{t}$+LF (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+C: "$t\\bar{t}$+C (4FS)"
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: "$t\\bar{t}$+B (4FS)"
    TTTo2L2Nu : "$t\\bar{t}$ dilepton"
    SingleTop : "Single t"
    WJetsToLNu_HT : "W+jets"
    ttHTobb: "$t\\bar{t}H$"

  colors_mc:
    ttHTobb: CMS_red
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: CMS_dark_orange
    TTToSemiLeptonic__TTToSemiLeptonic_tt+C: CMS_orange
    TTToSemiLeptonic__TTToSemiLeptonic_tt+LF: CMS_blue
    TTTo2L2Nu: CMS_brown
    SingleTop: CMS_gray
    WJetsToLNu_HT: CMS_purple

  exclude_samples:
    - ttHTobb_ttToSemiLep
    - TTToSemiLeptonic__TTToSemiLeptonic_tt+B
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+LF
    - TTbbSemiLeptonic__TTbbSemiLeptonic_tt+C

  rescale_samples:
    TTbbSemiLeptonic__TTbbSemiLeptonic_tt+B: 1.0

  opts_sig:
    histtype: "step"
    stack: false
    flow: "sum"
    edges: true
    linestyle: solid
    linewidth: 1

  blind_hists:
    categories: [semilep, SR, 4jSR, 5jSR, '>=6jSR']
    histograms:
      spanet_tthbb_transformed: [0.6, 1.0]
      spanet_tthbb: [0.6, 1.0]
